/**
 * Created by codecosine on 16-8-16.
 */
export const INIT_OPTION = 'INIT_OPTION';
export const UPDATE_OPTION = 'UPDATE_OPTION';
export const UPDATE_TYPE = 'UPDATE_TYPE';
// Auth
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_REQUEST_FINISH = 'SIGNIN_REQUEST_FINISH';

// CHARTITEMS
export const UPDATE_CHART_ITEMS = 'UPDATE_CHART_ITEMS';
export const CREATE_CHART = 'CREATE_CHART';
export const DELETE_CHART = 'DELETE_CHART';

// storage
export const UPDATE_CURRENT_NAME = 'UPDATE_CURRENT_NAME';
export const UPDATE_SERIES_NAME = 'UPDATE_SERIES_NAME';
export const UPDATE_RAW_DATA = 'UPDATE_RAW_DATA';

// CREATE EDIT FORM
export const UPDATE_CHART_ID = 'UPDATE_CHART_ID';
